language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
    - GOGS_DIR=/home/travis/gogs
    - DEP_DIR=/home/travis/dep
    - EXAMPLES_DIR=/home/travis/examples
    - JAVA_OPTS=-Xmx1024m -XX:MaxPermSize=256m
jdk:
  - oraclejdk8
script: ./gradlew check --info --stacktrace --max-workers=1
after_success:
  - ./gradlew jacocoTestReport coveralls
  - free -mt

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - git config --global user.email 'bo@gradle.com'
  - git config --global user.name 'Bo'

before_install:
  - mkdir ~/gogs && git clone https://github.com/gogits/gogs.git ~/gogs
  - mkdir ~/dep && git clone https://github.com/golang/dep.git ~/dep
  - mkdir ~/examples && git clone https://github.com/gogradle/examples.git ~/examples
  - free -mt

after_failure:
  - free -mt
  - cat /home/travis/gogs/.gogradle/reports/test/packages/*
  - cat /home/travis/gogs/.gogradle/reports/test/classes/*
  - cat /home/travis/gogs/.gogradle/reports/test/index.html

sudo: required
dist: trusty



